set(_CATKIN_CURRENT_PACKAGE "turtle_vis")
set(turtle_vis_VERSION "0.0.0")
set(turtle_vis_MAINTAINER "Emmanuel Dean <dean@tum.de>, Karinne Ramirez <karinne.ramirez@tum.de>")
set(turtle_vis_PACKAGE_FORMAT "1")
set(turtle_vis_BUILD_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "tf_conversions" "visualization_msgs" "message_generation")
set(turtle_vis_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "tf_conversions" "visualization_msgs" "message_run")
set(turtle_vis_BUILDTOOL_DEPENDS "catkin")
set(turtle_vis_BUILDTOOL_EXPORT_DEPENDS )
set(turtle_vis_EXEC_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "tf_conversions" "visualization_msgs" "message_run")
set(turtle_vis_RUN_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "tf_conversions" "visualization_msgs" "message_run")
set(turtle_vis_TEST_DEPENDS )
set(turtle_vis_DOC_DEPENDS )
set(turtle_vis_URL_WEBSITE "")
set(turtle_vis_URL_BUGTRACKER "")
set(turtle_vis_URL_REPOSITORY "")
set(turtle_vis_DEPRECATED "")